name = "temp-mail-console"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "temp-email-db"
database_id = "1e14e0c7-f183-4bd4-a136-bc65e2320ffa"

[triggers]
crons = ["0 * * * *"] # 每小时执行一次，检查并清理超过48小时的数据
